controllers/AuthController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\services\AuthService;
use app\forms\auth\LoginForm;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

class AuthController extends Controller
{

    private $authService;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['login'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function __construct($id, $module, AuthService $service, $config = array())
    {
        $this->authService = $service;
        parent::__construct($id, $module, $config);
    }

    public function actionLogin()
    {
        $form = new LoginForm();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $user = $this->authService->auth($form);
                Yii::$app->user->login($user, $form->rememberMe ? 3600 * 24 * 30 : 0);
                return $this->goHome();
            } catch (\DomainException $e) {
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }
        $form->password = '';
        return $this->render('index', [
                    'model' => $form,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

}

controllers/SignupController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\services\SignupService;
use yii\filters\AccessControl;
use app\forms\auth\SignupForm;

class SignupController extends Controller
{

    private $signupService;

    public function __construct($id, $module, SignupService $service, $config = array())
    {
        $this->signupService = $service;
        parent::__construct($id, $module, $config);
    }

    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $form = new SignupForm();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $this->signupService->signup($form);
                Yii::$app->session->setFlash('success', 'Вы успешно зарегестрировались!');
                return $this->goHome();
            } catch (\DomainException $e) {
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('index', [
                    'model' => $form,
        ]);
    }

}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\entities\User;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\forms\manage\UserForm;
use app\services\manage\UserManageService;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{

    private $userManage;

    public function __construct($id, $module, UserManageService $users, $config = array())
    {
        $this->userManage = $users;
        parent::__construct($id, $module, $config);
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => User::find(),
        ]);

        return $this->render('index', [
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $form = new UserForm();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $this->userManage->setRole($model->id, $form);
                Yii::$app->session->setFlash('success', 'Роль успешно изменена');
                return $this->goHome();
            } catch (\DomainException $e) {
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('update', [
                    'model' => $form,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->userManage->delete($id);

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\NavBar;
use app\assets\AppAsset;
use yii\helpers\Url;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php $this->registerCsrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
        <?php $this->beginBody() ?>

        <div class="wrap">
            <?php
            NavBar::begin();
            NavBar::end();
            ?>

            <div class="container">
                <div class="container">
                    <div class="row form-group">
                        <div class="col-xs-12 col-md-offset-2 col-md-8 col-lg-8 col-lg-offset-2">
                            <?= Alert::widget() ?>
                            <div class="panel panel-primary">
                                <div class="panel-heading">
                                    <span class="glyphicon glyphicon-comment"></span> Чат
                                    <div class="btn-group pull-right">
                                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                            <span class="glyphicon glyphicon-chevron-down"></span>
                                        </button>
                                        <ul class="dropdown-menu slidedown">
                                            <li><a href="<?= Url::to(['/site/index']); ?>"><span class="glyphicon glyphicon-refresh">
                                                    </span>Главная</a></li>
                                            <?php if (Yii::$app->user->can('admin')): ?>
                                                <li><a href="<?= Url::to(['/user/index']); ?>"><span class="glyphicon glyphicon-user">
                                                        </span>Пользователи</a></li>

                                                <li><a href="<?= Url::to(['/manage/index']); ?>"><span class="glyphicon glyphicon-remove">
                                                        </span>Черный список</a></li>
                                            <?php endif; ?>
                                            <li class="divider"></li>
                                            <?php if (Yii::$app->user->isGuest): ?>
                                                <li><a href="<?= Url::to(['/auth/login']); ?>"><span class="glyphicon glyphicon-off"></span>
                                                        Вход</a></li>
                                                <li><a href="<?= Url::to(['/signup/index']); ?>"><span class="glyphicon glyphicon-ok-sign">
                                                        </span>Регистрация</a></li>
                                            <?php else : ?>
                                                <li><a href="<?= Url::to(['/auth/logout']); ?>" data-method='POST'><span class="glyphicon glyphicon-off"></span>
                                                        Выход</a></li>
                                            <?php endif; ?>
                                        </ul>
                                    </div>
                                </div>
                                <?= $content ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer">
        <div class="container">
            <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

            <p class="pull-right"><?= Yii::powered() ?></p>
        </div>
    </footer>

    <?php $this->endBody() ?>
</body>
</html>
<?php $this->registerCssFile("@web/css/chat.css"); ?>
<?php $this->endPage() ?>