controllers/SiteController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use app\services\MessagesService;
use app\forms\chat\SendForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\ForbiddenHttpException;

class SiteController extends Controller
{

    private $messagesService;

    public function __construct($id, $module, MessagesService $messagesService, $config = array())
    {
        $this->messagesService = $messagesService;
        parent::__construct($id, $module, $config);
    }

    public function actionIndex()
    {
        $form = new SendForm();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            if (Yii::$app->user->isGuest) {
                throw new ForbiddenHttpException('Access denied');
            }
            try {
                $this->messagesService->send($form);
                return $this->refresh();
            } catch (\DomainException $e) {
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }
        return $this->render('index', [
                    'model' => $form,
                    'messages' => (Yii::$app->user->can('admin')) ? $this->messagesService->getMsgForAdmin() : $this->messagesService->getAllMessages(),
        ]);
    }

    public function actionComplaint($id)
    {
        try {
            $message = $this->messagesService->getMessage($id);
            $this->messagesService->complaint($message);
            Yii::$app->session->setFlash('success', 'Сообщение помечено как нежелательное.');
            return $this->goHome();
        } catch (\DomainException $e) {
            Yii::$app->session->setFlash('error', $e->getMessage());
            return $this->goHome();
        }
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['complaint'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'actions' => ['index', 'error'],
                        'allow' => true,
                        'roles' => ['?', '@'],
                    ],
                ],
            ],
        ];
    }

}

views/site/_form.php
<?php

use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
?>


<?php $form = ActiveForm::begin(); ?>
<?= $form->field($model, 'content')->label('Сообщение')->textarea(['class' => 'form-control', 'rows' => '3']); ?>
<!--<textarea class = "form-control" rows = "3"></textarea>-->
<span class = "col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-xs-12" style = "margin-top: 10px">
    <?= Html::submitButton('Отправить', ['class' => 'btn btn-warning btn-lg btn-block', 'id' => 'btn-chat']); ?>
    <?php $form = ActiveForm::end(); ?>
</span>


views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
/* @var $this yii\web\View */
/* @var $model app\forms\chat\SendForm */

use yii\helpers\Html;
use app\helpers\CutUsername;

$this->title = 'Chat';
?>

<div class="panel-body body-panel">
    <ul class="chat">
        <?php if (!$messages) : ?>
            <p>Еще никто ничего не написал..</p>
        <?php else: ?>
            <?php foreach ($messages as $message): ?>
                <li class="left clearfix"><span class="chat-img pull-left">
                        <img src="http://placehold.it/50/55C1E7/fff&text=<?= CutUsername::cutUsername($message->users->username); ?>" alt="User Avatar" class="img-circle" />
                    </span>

                    <div class = "chat-body clearfix">
                        <div class = "header">
                            <strong class = "primary-font">
                                <?php if ($message->users->isAdmin()): ?>
                                <i><?= Html::encode($message->users->username); ?></i></strong> <i>(admin)</i>
                            <?php else: ?>
                                    <?= Html::encode($message->users->username); ?></strong>
                                <?php endif; ?>
                            <small class = "pull-right text-muted">
                                <?php if (Yii::$app->user->can($message->users::ROLE_ADMIN) && $message->isAvaible()): ?>        
                                    <?= Html::beginForm(['/site/complaint', 'id' => $message->id]); ?>    
                                    <span class = "glyphicon glyphicon-time"></span><?= Yii::$app->formatter->asRelativeTime($message->created_at); ?>
                                    <?= Html::submitButton('Жалоба', ['class' => 'btn btn-danger btn-xs']); ?>
                                    <?= Html::endForm(); ?>
                                <?php else: ?>
                                    <span class = "glyphicon glyphicon-time"></span><?= Yii::$app->formatter->asRelativeTime($message->created_at); ?>
                                <?php endif; ?>
                            </small>

                        </div>
                        <p>
                            <?php if ($message->users->isAdmin() && $message->isDisable()): ?>
                                <i><s><?= Html::a(Html::encode($message->content), ['/manage/index']); ?></s></i>
                            <?php elseif ($message->users->isAdmin()) : ?>
                                <i><?= Html::encode($message->content); ?></i>
                            <?php elseif ($message->isDisable()): ?>
                                <s><?= Html::a(Html::encode($message->content), ['/manage/index']); ?></s>
                            <?php else: ?>
                                <?= Html::encode($message->content); ?>
                            <?php endif; ?>
                        </p>
                    </div>
                </li>
            <?php endforeach; ?>
        <?php endif; ?>
    </ul>
</div>
<div class = "panel-footer clearfix">
    <?php
    if (!Yii::$app->user->isGuest) {
        echo $this->render('_form', [
            'model' => $model,
        ]);
    }
    ?>